// ! Õld code not used
// const fs = require('fs');

// fs.writeFileSync('notes.txt', 'This file was generated by node js!');

// try {
//   fs.appendFileSync('notes.txt', ', message added by appendFileSync!');
// } catch (error) {
//   console.log(error);
// }
// const add = require('./utils');
// const getNotes = require('./notes');

// const sum = add(4, -2);
//  const msg = getNotes();

// console.log(sum);
// console.log(msg);
// const validator = require('validator');
// console.log(validator.isEmail('andrew@example.com'));
const getNotes = require('./notes');
// * load chalk
const chalk = require('chalk');

const command = process.argv[2];
console.log(process.argv);

if (command === 'add') {
  console.log('Adding note!');
} else if (command === 'remove') {
  console.log('Removing note');
}
